pyweb/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
# 127.0.0.1:8000/common/login
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

pyweb/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),                      # 127.0.0.1:8000/
    path('pybo/', include('pybo.urls')),        # 127.0.0.1:8000/pybo/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
]

pyweb/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    # 127.0.0.1:8000/pybo/
    path('', views.index, name='index'),
    path('board/', views.board, name='board'),
    # 127.0.0.1:8000/pybo/1/
    path('<int:question_id>/', views.detail, name='detail'),
    # 127.0.0.1:8000/question/create/   질문 등록
    path('question/create/', views.question_create, name='question_create'),
    # 답변 등록
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

pyweb/common/models.py
from django.db import models

# Create your models here.

pyweb/pybo/models.py
from django.contrib.auth.models import User
from django.db import models
# Question, Answer 모델 생성

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.content

pyweb/common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    
    class Meta:
        model = User
        fields = ("username", "email")  # 튜플 구조

pyweb/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta: # 중첩 클래스(내부 클래스)
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '질문 내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {'content': '답변 내용'}

pyweb/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

from common.forms import UserForm

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save() # 회원 저장
            # 가입과 동시에 자동로그인
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)  # user 객체 생성
            login(request, user)    # 로그인한 사용자(세션이 발급된 user)
            return redirect('pybo:index')
    else:
        form = UserForm()
    context = {'form': form}
    return render(request, 'common/signup.html', context)

pyweb/pybo/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from pybo.models import Question
from pybo.forms import QuestionForm, AnswerForm

def index(request):
    return render(request, 'pybo/index.html')

# 전체 목록 조회
def board(request):
    
    # 페이지
    page = request.GET.get('page', '1')
    
    # 조회
    question_list = Question.objects.order_by('-create_date')   # 내림차순 정렬

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)

# 상세 페이지 조회
def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/detail.html', context)

# 질문 등록
@login_required(login_url='common:login')
def question_create(request):
    if request.method =='POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)  # 임시 저장
            question.create_date = timezone.now()   # 등록일
            question.author = request.user  # 세션권한이 있는 user(author)
            question.save() # 실제 저장
            return redirect('pybo:board')
    else:   # request.method =='GET'
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

# 답변 등록
@login_required(login_url='common:login')
def answer_create(request, question_id):
    # question = Question.objects.get(id=question_id) # 질문 1개 가져오기
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question  # 질문을 답변에 저장(외래키)
            form.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form  = AnswerForm()
    context = {'form': form}
    return render(request, 'pybo:detail', context)

# 질문 수정
@login_required(login_url='common:login')
def question_modify(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # 세션권한이 있는 user 생성
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)  # 기존의 내용을 가져옴(question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

# 질문 삭제
@login_required(login_url='common:login')
def question_delete(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('pybo:index')

pyweb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello~ PyWeb!</title>
    <link rel="stylesheet" href="{% static 'pybo/css/bootstrap.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'pybo/css/style.css' %}"> -->
</head>
<body>
<!-- 네비게이션 바 -->
{% include 'navbar.html' %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- 햄버거 메뉴 -->
<script src="{% static 'pybo/js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'pybo/js/bootstrap.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}

{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

pyweb/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>
                또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a>
            </span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <!-- 에러 처리-->
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

pyweb/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

pyweb/templates/form_errors.html
<!-- 오류 처리 -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!-- 필드 오류 출력 -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field.errors %}    <!-- 넌필드 오류 출력 -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

pyweb/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pyweb</a>
        <!-- 햄버거 버튼-->
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- 로그인 메뉴 -->
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}  <!-- 로그인이 되었다면 -->
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pybo:board' %}">질문/답변</a>
                </li>
            </ul>
        </div>
    </nav>
</body>
</html>

pyweb/templates/pybo/detail.html
{% extends 'base.html' %}
<!-- base.html과 연결(상속, 확장) -->
{% block content %}
    <div class="container my-3">
        <!-- 질문 내용 -->
        <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line">
                    {{ question.content }}
                </div>
                <div class="d-flex justify-content-end">
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ question.author.username }}</div>
                        <div>{{ question.create_date }}</div>
                    </div>
                </div>
                {% if request.user == question.author %}
                <div class="my-3">
                    <a href="{% url 'pybo:question_modify' question.id %}"
                       class="btn btn-sm btn-outline-secondary">수정</a>
                    <a data-uri="{% url 'pybo:question_delete' question.id %}" href="#"
                       class="delete btn btn-sm btn-outline-secondary">삭제</a>
                </div>
                {% endif %}
            </div>
        </div>
        <h5 class="border-bottom my-3 py-2">
            {{ question.answer_set.count }}개의 답변이 있습니다.
        </h5>
        <!-- 답변 내용 -->
        {% for answer in question.answer_set.all %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space: pre-line">
                    {{ answer.content }}
                </div>
                <div class="d-flex justify-content-end">
                    <div class="badge badge-light p-2 text-left">
                        <div class="mb-2">{{ answer.author.username }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        <!-- 답편 폼 -->
        <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
            {% csrf_token %}
            <div class="form-group">
                <textarea name="content" id="content" rows="10" class="form-control"
                          {% if not user.is_authenticated %}disabled {% endif %}></textarea>
            </div>
            <input type="submit" value="답변 등록" class="btn btn-primary">
        </form>
    </div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
       $('.delete').on('click', function(){
          if(confirm("정말로 삭제하시겠습니까?")){
             location.href = $(this).data('uri');  // data-uri 경로 설정
          }
       });
    });
</script>
{% endblock %}

pyweb/templates/pybo/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="container">
    <div class="jumbotron">
        <div class="text-center"><h2>Welcome~ Have a nice Day!</h2>
        </div>
    </div>
    <div class="text-center">
        <img src="{% static 'pybo/images/coffee-blue.jpg' %}" id="pic">
    </div>
    <div>
        <p id="demo" class="text-center my-3"></p>
    </div>

</div>
{% endblock %}
{% block script %}
<script>
    // 메인 이미지 이벤트
    var pic = document.getElementById('pic')
    pic.addEventListener('mouseover', function(){
        pic.src = '../../static/pybo/images/coffee-pink.jpg';
    });

        pic.addEventListener('mouseout', function(){
        pic.src = '../../static/pybo/images/coffee-blue.jpg';
    });

    // 디지털 시계
    setInterval(myWatch, 1000)
    function myWatch(){
        var date = new Date();
        var now = date.toLocaleTimeString();
        document.getElementById('demo').innerHTML = now;
    }

</script>
{% endblock %}

pyweb/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류 표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류 표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

pyweb/templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
<!-- base.html과 연결(상속, 확장) -->
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-dark">
            <th>번호</th>
            <th style="width: 55%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list %}
            <tr>
                <!-- 전체게시물수 - 시작인덱스 - 현재인덱스 + 1 -->
                <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">
                        {{ question.subject }}
                    </a>
                </td>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
    <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">
                이전
            </a>
        </li>
        {% else %}
       <li class="page-item disabled">
            <a class="page-link" tableindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}

    <!-- 현재 페이지 -->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endfor %}
    <!-- 다음 페이지-->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">
                다음
            </a>
        </li>
        {% else %}
       <li class="page-item disabled">
            <a class="page-link" tableindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>

    <!-- 페이징 처리 끝 -->
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록</a>
</div>
{% endblock %}